site: Data Science by Design

baseurl: "/"

layout: default
comments: true

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
    type: "post"
  sp:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_posts/**"
      type: "posts"
    values:
      layout: "post"
      locale: en
  - scope: #2
      path: _posts/sp/**
      type: posts
    values:
      locale: sp

sass:
  sass_dir: assets/styles
  style: compressed
  sourcemap: never

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: "/blog/page:num/"

exclude:
  - .ruby-gemset
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - vendor/
